# Generated by Django 4.0.4 on 2022-07-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0009_alter_operation_high_proportion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('table', 'Table'), ('text', 'Text'), ('speech', 'Speech'), ('image', 'Image')], default='table', max_length=10),
        ),
    ]
